export type Lang='en'|'zh'|'es'
export type LocalText=Record<Lang,string>
export const t=(v:LocalText,l:Lang)=>v[l]

export const ui={
  demo:{en:'Demonstration Website / Sample Data',zh:'演示网站 / 模拟数据',es:'Sitio de demostración / Datos de muestra'},
  nav:{home:{en:'Home',zh:'首页',es:'Inicio'},products:{en:'Products',zh:'产品中心',es:'Productos'},solutions:{en:'Solutions',zh:'行业方案',es:'Soluciones'},cases:{en:'Case Studies',zh:'案例展示',es:'Casos'},about:{en:'About',zh:'关于我们',es:'Nosotros'},news:{en:'News',zh:'新闻资讯',es:'Noticias'},contact:{en:'Contact',zh:'联系我们',es:'Contacto'}},
  rfq:{en:'Request a Quote',zh:'获取报价',es:'Solicitar cotización'}, brochure:{en:'Download Brochure',zh:'下载产品手册',es:'Descargar catálogo'}, explore:{en:'Explore products',zh:'查看产品',es:'Ver productos'}, details:{en:'View details',zh:'查看详情',es:'Ver detalles'},
  sampleNote:{en:'All company, product, certification and case data shown here is fictional and for demonstration only.',zh:'本网站展示的公司、产品、认证与案例数据均为虚构，仅用于演示。',es:'Todos los datos de empresa, productos, certificados y casos son ficticios y solo para demostración。'}
}

export type Product={slug:string;name:LocalText;category:LocalText;tagline:LocalText;description:LocalText;features:LocalText[];applications:LocalText[];specs:{label:LocalText;value:string}[];sprite:number}
const L=(en:string,zh:string,es:string):LocalText=>({en,zh,es})
export const products:Product[]=[
 {slug:'nx-500-five-axis',name:L('NX-500 Five-Axis Center','NX-500 五轴加工中心','Centro de cinco ejes NX-500'),category:L('CNC Machining','数控加工','Mecanizado CNC'),tagline:L('Complex parts. One precise setup.','复杂零件，一次精准装夹','Piezas complejas en una sola sujeción'),description:L('A compact simulated machining platform for aerospace-style parts, dies and precision components.','面向航空类零件、模具与精密部件的紧凑型模拟加工平台。','Plataforma compacta simulada para piezas aeroespaciales, moldes y componentes de precisión.'),features:[L('Thermal compensation model','热误差补偿模型','Compensación térmica'),L('Direct-drive rotary table','直驱回转工作台','Mesa rotativa directa'),L('Tool monitoring ready','支持刀具监测','Preparado para monitoreo')],applications:[L('Precision components','精密部件','Componentes de precisión'),L('Die & mold','模具加工','Moldes y matrices')],specs:[{label:L('Travel X/Y/Z','行程 X/Y/Z','Recorrido X/Y/Z'),value:'500 / 600 / 450 mm'},{label:L('Spindle','主轴','Husillo'),value:'18,000 rpm'},{label:L('Positioning','定位精度','Posicionamiento'),value:'±0.006 mm*'}],sprite:0},
 {slug:'lf-3015-laser',name:L('LF-3015 Fiber Laser','LF-3015 光纤激光切割机','Láser de fibra LF-3015'),category:L('Laser Cutting','激光切割','Corte láser'),tagline:L('Clean cuts at production speed.','高速生产，洁净切割','Cortes limpios a velocidad productiva'),description:L('Enclosed sheet-metal cutting concept with intelligent nesting and extraction-ready architecture.','全封闭板材切割概念机型，支持智能排样与除尘架构。','Concepto cerrado para corte de chapa con anidado inteligente y extracción.'),features:[L('Enclosed safety cabin','全封闭安全舱','Cabina de seguridad'),L('Auto focus cutting head','自动调焦切割头','Cabezal de enfoque automático'),L('Nesting workflow','智能排样流程','Flujo de anidado')],applications:[L('Sheet metal','钣金加工','Chapa metálica'),L('Enclosures','机柜制造','Gabinetes')],specs:[{label:L('Working area','工作幅面','Área de trabajo'),value:'3000 × 1500 mm'},{label:L('Laser source','激光功率','Fuente láser'),value:'3–12 kW*'},{label:L('Repeatability','重复精度','Repetibilidad'),value:'±0.03 mm*'}],sprite:1},
 {slug:'rw-12-welding-cell',name:L('RW-12 Robotic Welding Cell','RW-12 机器人焊接工作站','Celda de soldadura RW-12'),category:L('Automation','自动化','Automatización'),tagline:L('Repeatable welds, protected workflow.','稳定焊缝，安全生产','Soldaduras repetibles, flujo protegido'),description:L('Modular robotic welding concept for medium-volume fabricated assemblies.','面向中等批量焊接结构件的模块化机器人工作站概念。','Concepto modular para conjuntos fabricados de volumen medio.'),features:[L('Modular guarding','模块化安全防护','Protección modular'),L('Offline programming ready','支持离线编程','Programación offline'),L('Fixture quick-change','夹具快速切换','Cambio rápido de utillaje')],applications:[L('Frames','金属框架','Bastidores'),L('Agricultural parts','农机部件','Piezas agrícolas')],specs:[{label:L('Payload','负载','Carga'),value:'12 kg'},{label:L('Reach','臂展','Alcance'),value:'1,440 mm'},{label:L('Repeatability','重复精度','Repetibilidad'),value:'±0.04 mm*'}],sprite:2},
 {slug:'pb-220-press-brake',name:L('PB-220 CNC Press Brake','PB-220 数控折弯机','Plegadora CNC PB-220'),category:L('Metal Forming','金属成形','Conformado'),tagline:L('Controlled force. Consistent angles.','可控压力，稳定角度','Fuerza controlada, ángulos constantes'),description:L('Servo-hydraulic bending concept for flexible sheet-metal production.','适合柔性钣金生产的伺服液压折弯概念机型。','Concepto servo-hidráulico para producción flexible de chapa.'),features:[L('Crowning compensation','挠度补偿','Compensación de coronado'),L('Graphical controller','图形化控制','Control gráfico'),L('Safety light curtain','安全光幕','Cortina de seguridad')],applications:[L('Electrical cabinets','电气柜','Armarios eléctricos'),L('HVAC panels','暖通板件','Paneles HVAC')],specs:[{label:L('Bending force','公称压力','Fuerza'),value:'2,200 kN'},{label:L('Length','折弯长度','Longitud'),value:'3,200 mm'},{label:L('Axes','控制轴数','Ejes'),value:'6-axis*'}],sprite:3},
 {slug:'ac-75-compressor',name:L('AC-75 VSD Compressor','AC-75 变频空压机','Compresor VSD AC-75'),category:L('Utilities','工业动力','Servicios industriales'),tagline:L('Demand-matched compressed air.','按需供气，稳定输出','Aire comprimido según demanda'),description:L('Variable-speed compressed-air package concept for industrial utility rooms.','适用于工业动力站房的变频压缩空气系统概念。','Concepto de aire comprimido de velocidad variable para plantas industriales.'),features:[L('Variable-speed drive','变频驱动','Variador de velocidad'),L('Remote status panel','远程状态面板','Panel remoto'),L('Integrated filtration','集成过滤','Filtración integrada')],applications:[L('General manufacturing','通用制造','Fabricación general'),L('Pneumatic tools','气动工具','Herramientas neumáticas')],specs:[{label:L('Motor power','电机功率','Potencia'),value:'75 kW'},{label:L('Working pressure','工作压力','Presión'),value:'7–13 bar*'},{label:L('Cooling','冷却方式','Refrigeración'),value:'Air cooled'}],sprite:4},
 {slug:'im-180-molding',name:L('IM-180 Injection Molder','IM-180 注塑机','Inyectora IM-180'),category:L('Plastics','塑料机械','Plásticos'),tagline:L('Stable cycles for technical parts.','稳定周期，精密成型','Ciclos estables para piezas técnicas'),description:L('Electric-hydraulic molding concept for technical polymer components.','用于工程塑料部件的电液复合注塑概念机型。','Concepto electrohidráulico para componentes de polímeros técnicos.'),features:[L('Closed-loop control','闭环控制','Control de lazo cerrado'),L('Energy monitoring','能耗监测','Monitoreo energético'),L('Recipe management','配方管理','Gestión de recetas')],applications:[L('Technical plastics','工程塑料','Plásticos técnicos'),L('Consumer components','消费品部件','Componentes de consumo')],specs:[{label:L('Clamping force','锁模力','Fuerza de cierre'),value:'1,800 kN'},{label:L('Shot weight','注射量','Peso de inyección'),value:'420 g*'},{label:L('Tie bar spacing','拉杆间距','Distancia de columnas'),value:'520 × 470 mm'}],sprite:5},
 {slug:'pk-60-packaging-line',name:L('PK-60 Packaging Line','PK-60 自动包装线','Línea de embalaje PK-60'),category:L('Packaging','包装自动化','Embalaje'),tagline:L('From infeed to sealed case.','从进料到封箱，一线完成','De entrada a caja sellada'),description:L('A modular end-of-line packaging concept for cartons and wrapped products.','面向纸箱与膜包产品的模块化后道包装线概念。','Concepto modular de fin de línea para cartones y productos envueltos.'),features:[L('Recipe-based changeover','配方化换型','Cambio por receta'),L('Vision check station','视觉检测工位','Inspección visual'),L('Expandable modules','模块化扩展','Módulos ampliables')],applications:[L('Food & beverage','食品饮料','Alimentos y bebidas'),L('Consumer goods','日用消费品','Bienes de consumo')],specs:[{label:L('Throughput','处理速度','Rendimiento'),value:'60 packs/min*'},{label:L('Line length','产线长度','Longitud'),value:'8.6 m'},{label:L('Control','控制系统','Control'),value:'PLC + HMI'}],sprite:6},
 {slug:'qc-bridge-cmm',name:L('QC-Bridge CMM','QC-Bridge 三坐标测量机','CMM QC-Bridge'),category:L('Quality Inspection','质量检测','Inspección'),tagline:L('Metrology confidence on the shop floor.','车间级计量信心','Confianza metrológica en planta'),description:L('Bridge-type coordinate measurement concept for dimensional verification.','用于尺寸验证的桥式三坐标测量概念设备。','Concepto de medición por coordenadas para verificación dimensional.'),features:[L('Granite base','花岗岩平台','Base de granito'),L('Temperature compensation','温度补偿','Compensación térmica'),L('Automated reports','自动报告','Informes automáticos')],applications:[L('First article inspection','首件检验','Primera pieza'),L('Process control','过程控制','Control de proceso')],specs:[{label:L('Measuring range','测量范围','Rango'),value:'800 × 1000 × 600 mm'},{label:L('Accuracy statement','精度说明','Precisión'),value:'Demo only*'},{label:L('Probe system','测头系统','Sistema de sonda'),value:'Touch trigger'}],sprite:7}
]

export const solutions=[
 {icon:'01',title:L('Automotive Components','汽车零部件','Componentes automotrices'),text:L('Flexible cells for machining, forming and inspection workflows.','覆盖加工、成形与检测流程的柔性单元。','Celdas flexibles para mecanizado, conformado e inspección.')},
 {icon:'02',title:L('Metal Fabrication','金属制造','Fabricación metálica'),text:L('From cutting and bending to protected robotic welding.','从切割折弯到安全的机器人焊接。','Desde corte y plegado hasta soldadura robotizada.')},
 {icon:'03',title:L('Consumer Packaging','消费品包装','Embalaje de consumo'),text:L('Modular automation designed around changeover and traceability.','围绕快速换型与追溯设计的模块化自动化。','Automatización modular para cambios y trazabilidad.')}
]

export const stories=[
 {sector:L('Metal fabrication','金属加工','Fabricación metálica'),title:L('A simulated path to shorter changeovers','缩短换型时间的模拟方案','Ruta simulada para cambios más cortos'),metric:'–32%*',note:L('Illustrative target, not an actual customer result.','示意目标，并非真实客户结果。','Objetivo ilustrativo, no resultado real.')},
 {sector:L('Parts machining','零件加工','Mecanizado'),title:L('Designing a compact unmanned cell','紧凑型无人单元设计','Diseño de celda compacta sin operador'),metric:'24/7*',note:L('Concept scenario only.','仅为概念场景。','Solo escenario conceptual.')},
 {sector:L('Packaging','包装行业','Embalaje'),title:L('One control layer across the line','整线统一控制层','Una capa de control para toda la línea'),metric:'1 UI*',note:L('Sample architecture only.','仅为示例架构。','Arquitectura de muestra.')}
]

export const articles=[
 {date:'2026.08.18',tag:L('ENGINEERING NOTE','工程笔记','NOTA TÉCNICA'),title:L('Five questions before specifying an automation cell','规划自动化单元前要问的五个问题','Cinco preguntas antes de definir una celda'),excerpt:L('A practical sample checklist covering takt time, parts, fixtures, safety and acceptance criteria.','从节拍、工件、夹具、安全与验收标准出发的示例检查清单。','Lista práctica sobre takt, piezas, utillaje, seguridad y aceptación.')},
 {date:'2026.07.29',tag:L('BUYER GUIDE','采购指南','GUÍA DE COMPRA'),title:L('How to compare machine proposals beyond price','如何在价格之外比较设备方案','Cómo comparar propuestas más allá del precio'),excerpt:L('Evaluate lifecycle support, process capability, utilities and integration scope.','从全生命周期支持、工艺能力、公用工程与集成边界综合评估。','Evalúe soporte, capacidad de proceso, servicios e integración.')},
 {date:'2026.06.12',tag:L('QUALITY','质量体系','CALIDAD'),title:L('Building an auditable sample acceptance plan','如何建立可审计的样机验收计划','Cómo crear un plan de aceptación auditable'),excerpt:L('Turn performance claims into measurable, witnessed acceptance criteria.','将性能承诺转化为可测量、可见证的验收标准。','Convierta promesas en criterios medibles y verificables.')}
]
